name: Golang Deploy
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v main.go
      - name: Generate Artifact
        run: ls -l
      - name: Upload Go build results
        uses: actions/upload-artifact@v4
        with:
          name: Go-Build
          path: main
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Download Artifact
       run: echo Descargando artifact